//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DovizProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlisSatislars
    {
        public int AlisSatisID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public int İslemTipiID { get; set; }
        public int DovizID { get; set; }
        public decimal Miktar { get; set; }
        public int VezneID { get; set; }
        public decimal İslemToplami { get; set; }
    
        public virtual Dovizlers Dovizlers { get; set; }
        public virtual IslemTipleris IslemTipleris { get; set; }
        public virtual Musterilers Musterilers { get; set; }
        public virtual Veznelers Veznelers { get; set; }
    }
}
