//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DovizProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dovizlers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dovizlers()
        {
            this.AlisSatislars = new HashSet<AlisSatislars>();
            this.Envanters = new HashSet<Envanters>();
        }
    
        public int DovizID { get; set; }
        public string DovizAdi { get; set; }
        public decimal DovizKuru { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlisSatislars> AlisSatislars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Envanters> Envanters { get; set; }
    }
}
