//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DovizProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Muhasebelers
    {
        public int MuhasebeID { get; set; }
        public int GelirGiderTipiID { get; set; }
        public int DovizID { get; set; }
        public decimal Miktar { get; set; }
        public string Aciklama { get; set; }
    
        public virtual GelirGiderTipleris GelirGiderTipleris { get; set; }
    }
}
